### PR TITLE
Add a `WildEmitter.mixin(<constructor>)` method for mixing emitter behaviour into a "class" more easily.

### PR DESCRIPTION
**Pull request by latentflip**
So I love WildEmitter, but I can literally never remember how to actually use it. And even when I read the docs I forget that I have to both inherit from a new Emitter, and do Emitter.call(this) in my constructor, I always forget one or the other.

This PR makes it as easy as

```javascript
var Emitter = require('wildemitter');

function Fruit () {
  //My own constructor code
}

Emitter.mixin(Fruit)
```

And doesn't break backwards compatibility.

### CODE REVIEW

**Comment by austinkelleher** [comment]
Is this something we are still interested in pursing? This was opened quite some time ago. @HenrikJoreteg

**Comment by HenrikJoreteg** [comment]
@austinkelleher i think it makes sense, if you want to get it done, i'm a +1.

**Comment by kohenkatz** [comment]
:+1: I like this. It looks so much cleaner than the old way.

**Comment by HenrikJoreteg** [comment]
I'm happy to merge this, but it's too out of sync with master. If someone wants to get it back up to speed, i'm happy to give them access to merge/publish.

**Comment by kohenkatz** [comment]
I'll make a new Pull Request

**Comment by HenrikJoreteg** [comment]
@kohenkatz i've added you as a contributor here as well. Happy to give you npm access too, just need your username there.

**Comment by kohenkatz** [comment]
Closing in favor of #15.

**Comment by kohenkatz** [comment]
@HenrikJoreteg Thanks. My npm username is the same as my Github - kohenkatz

**Pull request closed without merging**
